- hosts: webservers
  become: true
  tasks:
    - include_role:
        name: common
    - include_role:
        name: php74
    - include_role:
        name: memcached
      when: memcached.install == true
    - include_role:
        name: apache24
    - include_role:
        name: awscli2
      when: aws.cli.enable == true
