#-- MySQL5.7を入れる --#
- name: Install MySQL 5.7
  yum:
    name:
      - mysql-community-client
      - mysql-community-common
      - mysql-community-devel
      - mysql-community-libs
      - mysql-community-server
      - MySQL-python    # Ansibleの操作で必要
    state: present

#-- 設定ファイルをコピー --#
- name: Copy MySQL Config file
  template:
    src: "{{item.source}}"
    dest: "{{item.dest}}"
    owner: root
    group: root
    lstrip_blocks: yes
    trim_blocks: yes
  with_items:
    - { source: 'templates/my.cnf.j2', dest: '/etc/my.cnf' }

#-- 空のログファイルを作成 (slowquery) --#
- name: Create logfile - slowquery
  file:
    path: "{{ mysql.log.slowquery.path }}"
    state: touch
    owner: mysql
    group: mysql
  when: mysql.log.slowquery.enable == true

#-- 空のログファイルを作成 (general) --#
- name: Create logfile - general
  file:
    path: "{{ mysql.log.general.path }}"
    state: touch
    owner: mysql
    group: mysql
  when: mysql.log.general.enable == true
