#-- rootパスワード変更 --#
- name:  Change MySQL root password
  shell: echo "UPDATE mysql.user SET authentication_string=PASSWORD('{{mysql.root_pw}}') WHERE User='root'; FLUSH PRIVILEGES;" | mysql -u root

#-- /etc/my.cnfを書き換える --#
- name: Edit /etc/my.cnf
  lineinfile:
    dest: "/etc/my.cnf"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - { regexp: '^skip-grant-tables', line: '# skip-grant-tables' }
    - { regexp: '^skip-networking',   line: '# skip-networking' }

#-- MySQLを再起動 --#
- name: Restart MySQL
  service:
    name: mysqld
    state: restarted
