#-- rootパスワード変更 --#
- name:  Change MySQL root password1
  shell: echo "UPDATE mysql.user SET authentication_string=PASSWORD('{{tmppass}}') WHERE User='root'; FLUSH PRIVILEGES;" | mysql -u root

#-- /etc/my.cnfを書き換える --#
- name: Edit /etc/my.cnf
  lineinfile:
    dest: "/etc/my.cnf"
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
  with_items:
    - { regexp: '^skip-grant-tables', line: '# skip-grant-tables' }
    - { regexp: '^skip-networking',   line: '# skip-networking' }

#-- MySQLを再起動 --#
- name: Restart MySQL
  service:
    name: mysqld
    state: restarted

#-- rootパスワード変更 --#
- name:  Change MySQL root password2
  shell: echo "SET PASSWORD=PASSWORD('{{mysql.account.root.password}}'); FLUSH PRIVILEGES;" | mysql -u root -p{{tmppass}} --connect-expired-password
