#-- SELinuxの設定に必要なモジュールを入れる --#
- name: Install yum Module
  yum:
    name: libselinux-python
    state: installed

#-- SELinuxをOFFにする --#
- name: Disable SELinux
  selinux:
    state: disabled
  register: selinux

#-- 再起動 --#
- name: Reboot
  reboot:
    reboot_timeout: 600
  when: selinux.reboot_required

#-- 再起動が終わるまで待つ --#
- name: Wait Reboot
  local_action: wait_for host={{ inventory_hostname }} port={{ ansible_port }} delay=30
  when: selinux.reboot_required
  become: false
